version: '2'
services:
  postgres:
    image: postgres:10-alpine
    container_name: postgres
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    ports:
    - "5432:5432"
